# Specify output PDF documents here.
PDFS:=gpresentation.pdf example_paper.pdf

# Sources common to all documents:
common_depends:=$(wildcard common/fig/*)
common_videos:=$(wildcard common/video/*)

# Add the common directory to the common texinputs.
# NOTE: this list is *space* separated
EXTRA_PACKAGES:=common

# Sources for each document:

# Presentation has no references...
gpresentation_TEX:=example_presentation/presentation.tex
gpresentation_DEPENDS:=$(common_depends)
gpresentation_VIDEOS:=\
	$(wildcard example_presentation/video/*) $(common_videos)

# Paper does so we need to add an extra dependency...
gpaper_TEX:=example_paper/paper.tex
gpaper_DEPENDS:=$(wildcard example_paper/*.bib) $(common_depends)
gpaper_VIDEOS:=$(wildcard example_paper/video/*) $(common_videos)

# The magic is in here.
include scripts/latex.mk
